### ISSUE TITLE
Documento de Visão

### ISSUE THREAD

**Issue by Mateusas3s** [fga-gpp-mds/2018.1-Grupo2#11]
### Descrição
Elaboração do documento de visão

### Critérios de Aceitação
- [x] Apresentar tópicos base do documento 
- [x] Revisão do documento

### Tarefas
- [x] Introdução
- [x] Posiconamento
- [x] Descrição dos envolvidos
- [x] Visão Geral
- [x] Perspectiva do produto
- [x] Resumo de recursos
- [x] Recursos do Produto
- [x] Restrições
- [ ] Outros Requisitos do Produto

**Comment by daluzguilherme** [comment]
@lorryaze fechar a Isue #55 e reabrir por essa se o doc não estiver completo
