### ISSUE TITLE
Pesquisar serviços de host altenativos ao Heroku para deploy de produção

### ISSUE THREAD

**Issue by marlonguimaraes** [fga-gpp-mds/2018.1-Grupo2#111]
### Descrição
Atualmente o deploy de produção é feito no Heroku. Este serviço demonstrou ser instável e lento, não garantindo a segurança esperada de produção. Pesquisar serviços de maior qualidade, por exemplo Digital Ocean.

### Critérios de Aceitação
- [x]  Serviços viáveis (técnica e economicamente)

**Comment by aamandafelix** [comment]
Foi decidido que o heroku será mantido como host por ser um serviço gratuito e atender as atuais necessidades de projeto.
Caso seja necessário, esta issue será aberta novamente no futuro.
