### ISSUE TITLE
Definir critérios para a build falhar: critérios de análise estática, cobertura mínima de teste

### ISSUE THREAD

**Issue by marlonguimaraes** [fga-gpp-mds/2018.1-Grupo2#112]
### Descrição
A análise estática do código do repositório, bem como a cobertura de teste já estão incorporados na integração contínua (TravisCI), falta definir quando estas duas análises vão "quebrar a build".

### Critérios de Aceitação
- [x] Estar definido e incorporado ao TravisCI uma quantidade mínima de cobertura de código
- [x] Decidir quais "warnings" devem ou não quebrar a build do Travis

**Comment by aamandafelix** [comment]
Realizado em:
PR #144
PR #139
