### ISSUE TITLE
US17 - Gerar métricas de quanto tempo Pull-requests ficam abertos

### ISSUE THREAD

**Issue by daluzguilherme** [fga-gpp-mds/2018.1-Grupo2#116]
### Descrição
 Eu, como usuário, gostaria de visualizar métricas referentes ao tempo de pull-requests está em aberto para gerenciar o trabalho da equipe e alocar recursos quando necessário.

### Critérios de Aceitação
- [ ] Tempo de pull-requests com gráfico de barras. Parâmentros: tempo x quantidade de pull-requests
- [ ] Linha (limite) de tempo "saudável" de pull-request aberto

#### Tarefas

- Verificar como utilizar a lib do github para obter a data de abertura de todos os pull requests (tanto os ainda abertos e os já fechados) de um repositório e a data de fechamento de todos os pull requests que já foram fechados.

- Pesquisar e testar ferramentas para gerar gráficos na web/django. Dar prioridade para ferramentas mais "produtivas" e flexíveis.

**Comment by marlonguimaraes** [comment]
Inicialmente vamos definir "saudável" como até  **1 semana** o tempo desde a abertura do *Pull request* (PR). Isso quer dizer que PRs que estão abertos há mais de 7 dias ou que foram fechados depois de 7 dias serão considerados não-saudáveis. É necessário validar estes números com o time e cliente.
