### ISSUE TITLE
Nome do projeto

### ISSUE THREAD

**Issue by miguelnery** [fga-gpp-mds/2018.1-Grupo2#14]
### Descrição
Definir nome para o projeto.

### Critérios de Aceitação
- [ ] Nome escolhido ganhou a votação de nomes
- [ ] Não copia nomes existentes

### Tarefas
- [ ] Definir nomes para votação
- [ ] Votar nome

**Comment by marlonguimaraes** [comment]
Tarefa já incluida na issue https://github.com/fga-gpp-mds/2018.1-Grupo2/issues/12
