### ISSUE TITLE
TS03 - Refatorar código para armazenar no banco as requisições de qualquer repositório

### ISSUE THREAD

**Issue by Mateusas3s** [fga-gpp-mds/2018.1-Grupo2#142]
### Descrição
Refatorar código para armazenar no banco as requisições feita pela API, de qualquer repositório no Github

### Critérios de Aceitação
- [x] A requisição deve funcionar para qualquer repositório 
- [ ] Deve-se armazenar os dados no banco, referente ao repositório pesquisado
- [ ] Ao finalizar a visualização desse repositório, deve-se limpar os dados referentes a ele no banco

### Tarefas
- [x] Refatorar funções de requisição da API
- [x] Refatorar funções de armazenamento no banco

**Comment by jpmartins201** [comment]
Precisamos de ajuda nos testes (models e views).....
