### ISSUE TITLE
Problemas com o container cardinalsweb

### ISSUE THREAD

**Issue by jpmartins201** [fga-gpp-mds/2018.1-Grupo2#147]
### Descrição
Após rodar o comando "sudo docker-compose up -d", apenas o conteiner 20181cardinals_db_1 é iniciado, enquanto o conteiner cardinalsweb não funciona. 

---

![printbug](https://user-images.githubusercontent.com/30712408/40937940-ab4bf532-6816-11e8-8aa0-3ef7aaf5d746.jpg)

**Comment by aamandafelix** [comment]
Você está trabalhando em qual branch?
O que tá na imagem é o log completo do erro ou tem mais alguma informação?
Testei agora na `develop` e aparentemente tá tudo ok, funcionou.

Teste os seguintes comandos:
`$ sudo docker-compose down`
`$ sudo docker-compose build`
`$ sudo docker-compose up `

**Comment by jpmartins201** [comment]
Estava trabalhando na branch `develop` e também tinha testado esses comandos, mas ainda assim o conteiner cardinalsweb não funcionava. A imagem era para mostrar que ele não aparecia quando o comando `sudo docker ps` era executado

**Comment by aamandafelix** [comment]
Favor repetir os mesmos passos do comentário anterior, mas nessa branch e verificar se o erro continua:
https://github.com/fga-gpp-mds/2018.1-Cardinals/tree/hotfix_postgre-connection

**Comment by aamandafelix** [comment]
Possível solução dessa issue já se encontra na branch `develop`.

**Comment by jpmartins201** [comment]
Durante a execução do comando `sudo docker-compose logs -f` os dois conteineres não funcionam devido alguma alteração.
![captura de tela de 2018-06-05 11-45-45](https://user-images.githubusercontent.com/30712408/40993360-cf5199f0-68cf-11e8-97ed-baa1962e9ec7.png)

**Comment by aamandafelix** [comment]
Usuário relatou que problema foi resolvido.
