### ISSUE TITLE
Criar a view para a página inicial do projeto

### ISSUE THREAD

**Issue by marlonguimaraes** [fga-gpp-mds/2018.1-Grupo2#16]
### Descrição
Ao entrar na página inicial (/) deve ser apresentado um texto descrevendo brevemente do que se trata o projeto.

### Critérios de Aceitação
- [x] Texto sobre o projeto na página inicial
- [x] Testes unitários sobre o texto mostrado na página inicial

**Comment by daluzguilherme** [comment]
@amandabezerra , no treinamento (Issue #5 )  essa issue foi iniciada? Feita? Como ficou?
