### ISSUE TITLE
Corrigir bug do botão da funcionalidade ranking commiters.

### ISSUE THREAD

**Issue by lorryaze** [fga-gpp-mds/2018.1-Grupo2#163]
### Descrição
Corrigir bug do botão de ranking commiters, que desaparece quando estamos em outra funcionalidade e queremos mudar pra funcionalidade de ranqueamento dos commiters

### Tarefas
- [ ] correção de bug

---

### Sobre o que se trata esta issue? (Marque "x")
- [x] Relatório de bug
- [ ] Requisição de funcionalidade
- [ ] Necessito de suporte

### Descrição
Descreva seu problema ou requisição.

### Ambiente
Descreva seu sistema operacional, versões, etc...

### Comportamento atual:
Descreva o que está acontecendo.

### Comportamento esperado:
Descreva o que deveria acontecer.

### Como reproduzir esta issue?
Insira um passo-a-passo ou trechos de código para entendermos melhor seu problema.

```
reproduza seu código
```

**Comment by Mateusas3s** [comment]
vou dar um olhada

**Comment by Mateusas3s** [comment]
resolvida no merge acima
