### ISSUE TITLE
problema ao exportar imagem de gráficos

### ISSUE THREAD

**Issue by Mateusas3s** [fga-gpp-mds/2018.1-Grupo2#164]
### Sobre o que se trata esta issue? (Marque "x")
- [ ] Relatório de bug
- [ ] Requisição de funcionalidade
- [x] Necessito de suporte

### Descrição
Para poder usar a função que exporta um gráfico da biblioteca Bokeh é preciso que no conteiner tenha a biblioteca phantomjs. Documentação referente a essa funcionalidade: 
https://bokeh.pydata.org/en/latest/docs/user_guide/export.html#userguide-export 

![captura de tela de 2018-06-14 15-35-50](https://user-images.githubusercontent.com/18116735/41431303-d9edc12a-6fe8-11e8-9ade-1a5b0cf1f5b8.png)

**Comment by jpmartins201** [comment]
É necessário fazer a instalação da biblioteca phantomjs com o npm install
