### ISSUE TITLE
Funcionalidade de ranquear commiters com comportamento imprevisivel

### ISSUE THREAD

**Issue by marlonguimaraes** [fga-gpp-mds/2018.1-Grupo2#175]
Do ponto de vista do usuário, ao ranquear os commiters para o repositório `fgacardinals/test_commiters`, a lista de pontos retornadas é; `(193.0, 34.0)`. Porém, nos testes unitários para esta funcionalidade os valores retornados são `(208.91, 12.09)`, o que torna a pontuação imprevísvel.

**Comment by marlonguimaraes** [comment]
Arquivo de testes: https://github.com/fga-gpp-mds/2018.1-Cardinals/blob/test_coverage/ranking_commiters/tests.py

**Comment by marlonguimaraes** [comment]
Pesos utilizados:

```python 
weights = {
                   'weight_commit': 3,
                    'weight_line_code': 2,
                    'weight_issues_created': 5,
                    'weight_issues_closed': 10,
                  }
```

**Comment by Mateusas3s** [comment]
* Limpa o banco de dados com os seguintes comandos:
find . -path "*/migrations/*.py" -not -name "__init__.py" -delete
find . -path "*/migrations/*.pyc"  -delete

* derruba o container:
docker-compose down

* sobe ele novamente:
docker-compose up -d
