### ISSUE TITLE
Migrar documentos da wiki para o github pages (/docs)

### ISSUE THREAD

**Issue by marlonguimaraes** [fga-gpp-mds/2018.1-Grupo2#21]
### Descrição
Migrar toda a documentação para o github pages

### Critérios de Aceitação
- [x] Pasta docs na raíz do repositório
- [ ] Github pages completo em relação a wiki
- [x] Páginas da wiki deletadas

**Comment by marlonguimaraes** [comment]
@lucasca73 A wiki vai ser deletada? Se não for, retire estre critério de aceitação e feche a issue.

**Comment by daluzguilherme** [comment]
Pessoal, vamos tirar o débito dessa issue, falta apenas subir a página do docs. @lucasca73 consegue fazer pra até essa quinta (05/04)?
