### ISSUE TITLE
Bug no Docker

### ISSUE THREAD

**Issue by Mateusas3s** [fga-gpp-mds/2018.1-Grupo2#22]
Mensagem de erro apresentada ao tentar rodar o docker:

mateusas3s@mateusas3s:~/MDS/2018.1-Cardinals$ sudo docker-compose up -d
20181cardinals_db_1 is up-to-date
Starting 20181cardinals_web_1 ... error

ERROR: for 20181cardinals_web_1  Cannot start service web: driver failed programming external connectivity on endpoint 20181cardinals_web_1(3dd65591c6bc3e5cfe3e58ccaf45fcde163a59b7405a12ae95da037de868a0e7): Bind for 0.0.0.0:8000 failed: port is already allocated

ERROR: for web  Cannot start service web: driver failed programming external connectivity on endpoint 20181cardinals_web_1 (3dd65591c6bc3e5cfe3e58ccaf45fcde163a59b7405a12ae95da037de868a0e7): Bind for 0.0.0.0:8000 failed: port is already allocated
ERROR: Encountered errors while bringing up the project.

**Comment by marlonguimaraes** [comment]
O log diz que você já está "escutando" na porta 8000. Algumas possíveis soluções:

1. Termine o processo utilizando tal porta:

    ` $ sudo kill `sudo lsof -t -i:8000` (Stackoverflow) `

2. Reinicie os serviços:
` $ sudo docker-compose down `
` $ sudo docker-compose up `

3. Suba o servidor em uma porta diferente, 
 Mude a linha ` python manage.py runserver 0.0.0.0:8000 ` para ` python manage.py runserver 0.0.0.0:8888 `, no arquivo [run.sh](https://github.com/fga-gpp-mds/2018.1-Cardinals/blob/develop/run.sh) (linha 5)

**Comment by marlonguimaraes** [comment]
Issue fechada, caso seja relatado mais problemas em relação a issue, ela será reaberta.

**Comment by Mateusas3s** [comment]
Funcionou, tudo ok com o docker agora.

**Comment by marlonguimaraes** [comment]
O problema parece similiar com este problema do docker-compose: https://github.com/docker/for-mac/issues/205

Uma solução comentada foi essa:

1. `sudo docker-compose down`
2. `sudo docker rm -f $(docker ps -aq)`
3. `sudo service docker restart`
4. `sudo docker-compose up`
