### ISSUE TITLE
Problemas execução do projeto

### ISSUE THREAD

**Issue by RochaCarla** [fga-gpp-mds/2018.1-Grupo2#31]
Pessoal,

vocês estão bastante atrasados na disciplina. Aqui vão alguns feedbacks:

- [ ]  Não há transparência no projeto de vcs (documentação das sprints não está up to date)

- [ ]  Vocês estão pecando bastante na execução da metodologia. Scrum Master não está fazendo o trabalho direito ( o que aconteceu nas duas primeiras sprints? apenas 3 issues??)

- [x] Cadê a pontuação das tarefas? já eram para estar pontuando

- [x] Descrição das issues está OK. Porém, vcs não estão usando as issues como canal de comunicação e rastreio da execução da propria issue

- [x] O kanban de vocês (colunas) não reflete o fluxo de trabalho da equipe

- [x] Sugestão: detalhar mais as issues usando mais labels 

- [ ] A falta de transparência (documentação das sprints atualizadas, execução da metodologia) dificulta a gestão de risco do projeto. Por exemplo, não está claro em qual fase/etapa do projeto vocês se encontram, qual o roadmap proposto, quando vocês começam a desenvolver o produto, cadê o protótipo, etc

**Comment by marlonguimaraes** [comment]
Problemas resolvidos/se resolvendo.
