### ISSUE TITLE
US02 - Atribuir Pesos a Critérios de Ranqueamento

### ISSUE THREAD

**Issue by daluzguilherme** [fga-gpp-mds/2018.1-Grupo2#36]
### Descrição
Eu como usuário, gostaria de atribuir pesos a critérios de ranqueamento para que possa ranquear os commiters de acordo com os critérios escolhidos por mim.

### Critérios de Aceitação
- [x] Diferentes Pesos devem ser considerados para ranquemanto de *commiters*
- [x] Pesos podem sofrer alteração pelo usuário

### Tarefas
- [x] Criar critérios de ranqueamento que o usuário pode escolher (ranquear por nº de linhas de código, por nº de commits etc)
- [ ] Frontend de acordo com o protótipo

**Comment by Mateusas3s** [comment]
Além de pontuar o contribuidor por ter criado a issue seria bom ele ser pontuado por ter seu nome assinado na issue

**Comment by daluzguilherme** [comment]
Critérios:
* Quantidade de commits;
* Linhas de código modificadas;
* Issues abertas;
* Issues fechadas;
* Pull-requests aceitos; 
* Quantidade de commits pareados

Abrir detalhes dos contribuidores nos rankings ao clicar no nome

Ranqueamento vai ser feia por combinação linear dos critérios
