### ISSUE TITLE
US08 - Verificar existência de documento de descrição do projeto

### ISSUE THREAD

**Issue by daluzguilherme** [fga-gpp-mds/2018.1-Grupo2#44]
### Descrição
Eu como usuário, gostaria de verificar se existe o documento referente à descrição do projeto para que possa haver uma diretriz de comunicação completa sobre o projeto.

### Critérios de Aceitação
- [ ]  Se o documento de política de contribuição for encontrado, deve aparecer um "check" verde (:heavy_check_mark:) ao lado do nome do documento
- [ ] Se o o documento não existir no repositório, deve aparecer um "X" vermelho (:x:) ao lado do nome do documento

### Tarefas
[ ] Testes

**Comment by marlonguimaraes** [comment]
### Tarefas
[ ] Testes
