### ISSUE TITLE
US11 - Obter Métricas de Issues abertas e fechadas

### ISSUE THREAD

**Issue by daluzguilherme** [fga-gpp-mds/2018.1-Grupo2#48]
### Descrição
Eu como usuário gostaria de ver métricas com base nas issues abertas e fechadas do repositório, para que possa identificar movimentação e gerenciamento organizacional do projeto.

### Critérios de Aceitação
- [x] Quantidade de Issues abertas em determinado tempo
- [ ] Quantidade de Issues fechadas em determinado tempo
- [ ] O usuário pode escolher o intervalo de tempo a ser analisado

### Tarefas
- [x] Obter todas issues do repositório através da API
- [x] Filtrar Issues pelo tempo
- [x] Frontend de acordo com o protótipo

**Comment by daluzguilherme** [comment]
Definir critérios de aceitação com P.O. @joaaogui

**Comment by marlonguimaraes** [comment]
- Filtro por tempo de issues fechadas (data de fechamento) não está funcionando adequadamente
- Adicionar testes
