### ISSUE TITLE
US12 - Gerar Métricas de commits por período

### ISSUE THREAD

**Issue by daluzguilherme** [fga-gpp-mds/2018.1-Grupo2#50]
### Descrição
Eu, como usuário gostaria de visualizar o número de commits que um determinado usuário realizou num dado intervalo de tempo.

### Critérios de Aceitação
- [x] Quantidade de *commits* de cada usuário em determinado tempo
- [ ] O usuário pode escolher o intervalo de tempo a ser analisado

### Tarefas
- [x] Frontend de acordo com o protótipo

**Comment by daluzguilherme** [comment]
Definir critério de aceitação com P.O @joaaogui

**Comment by mdscardinals** [comment]
Aparentemente as Issues #50 e #51 estão pedindo a mesma funcionalidade. Vocês podem verificar?
Ass. Gustavo

**Comment by daluzguilherme** [comment]
São diferentes, a issue #50 se refere aos commits de cada contribuidor do repositório enquanto a issue #51 se refere aos commits gerais/totais do repositório

**Comment by marlonguimaraes** [comment]
- Filtro por tempo não está funcionando adequadamente
- Adicionar testes

**Comment by daluzguilherme** [comment]
Cliente não conseguiu ver valor nesta história
