### ISSUE TITLE
US13 - Fornecer número de commits realizados no repositário em um dado intervalo de tempo

### ISSUE THREAD

**Issue by daluzguilherme** [fga-gpp-mds/2018.1-Grupo2#51]
### Descrição
Eu, como usuário gostaria de visualizar o número total de commits realizados em um dado repositório durante um intervalo de tempo, de acordo a data de início e data final, por exemplo de 15/07/2018 até 15/09/2018.

### Critérios de Aceitação
- [ ] Data final tem que ser maior ou igual que a data inicial
- [ ] Não pode haver datas no futuro
- [ ] Não pode analizar datas anteriores a data de criaçao de repositório

### Tarefas
- [ ] Testes

**Comment by marlonguimaraes** [comment]
História não implementada.

**Comment by daluzguilherme** [comment]
Cliente não viu valor na história
