### ISSUE TITLE
Documento de Visão

### ISSUE THREAD

**Issue by lorryaze** [fga-gpp-mds/2018.1-Grupo2#55]
### Critérios de Aceitação
- [x] Apresentar tópicos base do documento
- [x] Atualizações sobre a organização do Documento

### Tarefas
- [x] Introdução. @lorryaze
- [x] Posicionamento
- [x] Descrição dos Envolvidos
- [x] Visão geral do produto
- [x] Recursos do produto 
- [x] Restrições
- [x] Outros requisitos do produto @lorryaze
- [x] Referências Bibliográficas @lorryaze
- [x] Organização do documento @lorryaze

### Sobre o que se trata esta issue? (Marque "x")
- [ ] Relatório de bug
- [x] Requisição de funcionalidade
- [ ] Necessito de suporte

### Ambiente
Descreva seu sistema operacional, versões, etc...

### Comportamento atual:
Descreva o que está acontecendo.

### Comportamento esperado:
Descreva o que deveria acontecer.

### Como reproduzir esta issue?
Insira um passo-a-passo ou trechos de código para entendermos melhor seu problema.

```
reproduza seu código
```

**Comment by daluzguilherme** [comment]
@lorryaze Já existe uma issue para doc de visão. Issue #11 . Feche essa issue e reabra a outra se o documento não estiver completo

**Comment by lorryaze** [comment]
Finalizada
