### ISSUE TITLE
Treinamento de Testes

### ISSUE THREAD

**Issue by aamandafelix** [fga-gpp-mds/2018.1-Grupo2#6]
### Descrição
Treinamento de Testes para alunos de MDS.
Conteúdo previsto
- [x] Django unit tests
- [x] Selenium (?)

### Tarefas
- [x] Apresentar conceitos 
- [x] Realizar atividades práticas

**Comment by jpmartins201** [comment]
Treinamento realizado hoje, falta apenas o selenium agora

**Comment by daluzguilherme** [comment]
Treinamento concluído
