### ISSUE TITLE
Mudança de Feature Indicadores para métricas

### ISSUE THREAD

**Issue by lucasca73** [fga-gpp-mds/2018.1-Grupo2#63]
### Descrição
Com base em reunião geral do grupo, foi percebido que para gerar indicadores, é necessário um estudo para validar a veracidade de como a métrica gera o indicador. Isso será separado em uma feature futura. Agora será lidado com métricas em vez de indicadores, desse jeito a equipe de desenvolvimento fará entregas que possam contribuir melhor para o produto. Métricas serão geradas em cima dos dados vindos do repositório, como commits pelo tempo, razão de issues aberta e issues fechadas por tempo, e outras que serão detalhadas melhor nas histórias de usuário.

### Critérios de Aceitação
- [x] Labels atualizadas
- [x] Histórias atualizadas
- [x] Feedback do PO

---

### Sobre o que se trata esta issue? (Marque "x")
- [ ] Relatório de bug
- [ ] Requisição de funcionalidade
- [ ] Necessito de suporte
- [x] Adaptação de escopo

**Comment by lucasca73** [comment]
@sabrynaasousa  @joaaogui necessitamos de feedback em relação à essa adaptação para dar continuidade à essa feature.

**Comment by sabrynaasousa** [comment]
Pode ser feita essa adaptação, está ok!
