### ISSUE TITLE
Termo de Abertura do Projeto

### ISSUE THREAD

**Issue by aamandafelix** [fga-gpp-mds/2018.1-Grupo2#7]
### Descrição
Elaborar [Termo de Abertura de Projeto](https://github.com/fga-gpp-mds/2018.1-Cardinals/wiki/Termo-de-Abertura-do-Projeto)

### Critérios de Aceitação
- [ ] Critério...

### Tarefas
- [x] Sumário @amandabezerra 
- [x] Introdução @lucasca73 
- [x] Descrição do Projeto @marlonbymendes
- [x] Propósito do Projeto @MiguelNery 
- [x] Oportunidade de Negócio @amandabezerra 
- [x] Escopo do Projeto @lucasca73
- [x] Equipe e Papéis @MiguelNery
- [x] Prazo @marlonbymendes
- [x] Custo @daluzguilherme
- [x] Estratégia de Comunicação @amandabezerra
- [x] Referências Bibliográfica @lucasca73

**Comment by marlonbymendes** [comment]
Sumário @amandabezerra 
Introdução
Descrição do Projeto
Propósito do Projeto
Oportunidade de Negócio
Escopo do Projeto
Equipe e Papéis
Prazo
Custo
Estratégia de Comunicação
Referências Bibliográficas
