### ISSUE TITLE
Estrutura Analítica do Projeto

### ISSUE THREAD

**Issue by aamandafelix** [fga-gpp-mds/2018.1-Grupo2#8]
### Descrição
Elaborar Estrutura Analítica do Projeto

### Critérios de Aceitação
- [ ] Critério...

### Tarefas
- [ ] Tarefa...

**Comment by lucasca73** [comment]
@RochaCarla, Nós podemos orientar nossa EAP por entregas. Release -> Sprint -> US ?

**Comment by RochaCarla** [comment]
Sprint  e US são muito granulares. Nesse caso, sugiro que façam em release, ÉPICOS E Features (sendo que vcs ainda precisam colocar pacotes referentes à documentação e treinamentos)

**Comment by daluzguilherme** [comment]
Pessoal, vamos tirar o débito dessa issue com a aplicação da sugestão da professora.
@amandabezerra , @lucasca73 , @marlonbymendes , @MiguelNery
