### ISSUE TITLE
Cronograma de datas de início e fim de sprints e releases

### ISSUE THREAD

**Issue by marlonguimaraes** [fga-gpp-mds/2018.1-Grupo2#9]
Cronograma de datas de início e fim de sprints e releases

### Critérios de Aceitação
- [ ] Data de início e fim de todas as sprints, incluindo a sprint 0
- [ ] Datas das releases 1 e 2 destacadas

**Comment by miguelnery** [comment]
Cronograma em andamento no drive do grupo.
O cronograma da disciplina ainda não contempla as datas da Release 2 ou do fim das atividades do semestre, portanto, ainda não é possível planejar todas as sprints e a Release 2 no nosso cronograma.

**Comment by marlonguimaraes** [comment]
Cronograma atualizado: https://docs.google.com/spreadsheets/d/1t0PXF_8jH6dfqb_hxChGDPjtMchCeVijgsQG4XUZqt0/edit?usp=sharing

Revisem @daluzguilherme @MiguelNery, por favor.

**Comment by marlonguimaraes** [comment]
Data da release 2 ainda não definida.
