### ISSUE TITLE
Falha ao rodar o mekemigrations

### ISSUE THREAD

**Issue by Mateusas3s** [fga-gpp-mds/2018.1-Grupo2#91]
### Sobre o que se trata esta issue? (Marque "x")
- [x] Relatório de bug
- [ ] Requisição de funcionalidade
- [ ] Necessito de suporte

### Descrição

* Fui rodar o mekemigrations e foi gerado a seguinte mensagem abaixo:
<i>root@032ae477e9cd:/code# python manage.py makemigrations
/usr/local/lib/python3.6/site-packages/psycopg2/__init__.py:144: UserWarning: The psycopg2 wheel package will be renamed from release 2.8; in order to keep installing from binary please use "pip install psycopg2-binary" instead. For details see: <http://initd.org/psycopg/docs/install.html#binary-install-from-pypi>.
  """)
No changes detected</i>

* Depois instalei a dependência que é citada na mensagem:
<i>pip install psycopg2-binary
Collecting psycopg2-binary
  Downloading psycopg2_binary-2.7.4-cp36-cp36m-manylinux1_x86_64.whl (2.7MB)
    100% |████████████████████████████████| 2.7MB 335kB/s
Installing collected packages: psycopg2-binary
Successfully installed psycopg2-binary-2.7.4</i>

* Rodei novamente o makemigrations e recebia mensagem abaixo:
<i>No changes detected</i>

* Minha models.py está assim:

        from django.db import models

        class ProfileUser(models.Model):
              username = models.CharField(max_lenght=255, null=False)
              name = models.CharField(max_lenght=255, null=False)
              email = models.EmailField(max_lenght=255, null=False)

Observação:
    Quanto a dependência, eu percebi que nem essa e nem a do pygithub que estão no requirements.txt estão sendo instaladas ao rodar o docker

**Comment by aamandafelix** [comment]
A branch `develop` já possui o psycopg2-binary como dependência. 
Para resolver o problema:
1. Atualize sua branch com a develop
2. Utilize os seguintes comandos:
    `sudo docker-compose stop`
    `sudo docker-compose build`
    `sudo docker-compose up -d`
3. Rode novamente os comandos de migração no terminal do container

**Comment by daluzguilherme** [comment]
@Mateusas3s , esta solução funcionou?

**Comment by daluzguilherme** [comment]
Como relatado pelo autor da issue, a solução funcionou parcialmente, não interferindo atualmente no desenvolvimento. Fecharei  a issue e quando necessário o autor a reabrirá.
