### ISSUE TITLE
Erro 404 ao buscar repositórios

### ISSUE THREAD

**Issue by daluzguilherme** [fga-gpp-mds/2018.1-Grupo2#95]
### Descrição
- Ao buscar um repositório no campo de busca, um erro 404 - Not Found é exibido
---

### Sobre o que se trata esta issue? (Marque "x")
- [x] Relatório de bug
- [ ] Requisição de funcionalidade
- [ ] Necessito de suporte

### Como reproduzir esta issue?
No campo de busca na tela inicial buscar pelo repositório "github"

### Captura de Tela
![Imgur](https://i.imgur.com/0yk8JxN.png)

**Comment by Mateusas3s** [comment]
Esta é uma exceção que ainda será tratada. Ao inserir no campo de pesquisa um repositório não existente, ou o nome errado será retornado esse erro.
Para a pesquisa ser realizada com sucesso, deve-se inserir, até então, exatamente o nome do repositório.

**Comment by daluzguilherme** [comment]
Como o erra ainda está ocorrendo vou reabrir a issue e quando for corrigido feche a issue.

**Comment by daluzguilherme** [comment]
bug corrigido
