### ISSUE TITLE
Problemas com Build no Docker.

### ISSUE THREAD

**Issue by lorryaze** [fga-gpp-mds/2018.1-Grupo2#97]
### Descrição.
Estou com problemas para subir o Docker em branchs criadas a partir da develop.
---

### Sobre o que se trata esta issue? (Marque "x")
- [x] Relatório de bug
- [ ] Requisição de funcionalidade
- [ ] Necessito de suporte

### Descrição
Descreva seu problema ou requisição.

### Ambiente
Descreva seu sistema operacional, versões, etc...

### Comportamento atual:
Descreva o que está acontecendo.

### Comportamento esperado:
Descreva o que deveria acontecer.

### Como reproduzir esta issue?
Insira um passo-a-passo ou trechos de código para entendermos melhor seu problema.

```
reproduza seu código
```

**Comment by marlonguimaraes** [comment]
Publique os logs de erros e/ou mensagens relacionadas, ou publique uma print dos mesmos
